apiVersion: apps/v1
kind: Deployment
metadata:
  name: knative-statemachine-runner
  labels:
    app: runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runner 
  template:
    metadata:
      labels:
        app: runner 
    spec:
      containers:
      - name:  runner
        image: ko://github.com/salaboy/knative-statemachine-runner
        env:
          - name: STATEMACHINE_DEF
            valueFrom:
              configMapKeyRef:
                name: statemachine
                key: statemachine-buy-tickets.yaml
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: knative-statemachine-runner-service
spec:
  selector:
    app: runner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
